name: CI of re-engine-GNU

on:
  push:
  pull_request:
 
jobs:
  windows:
    name: Windows cl
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
          - amd64_arm64
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        arch: ${{ matrix.arch }}
    - name: Use Makefile.PL
      run: |
        perl -V
        cpan App::cpanminus
        cpanm --cpanfile cpanfile --installdeps --with-configure .
        perl Makefile.PL
        make
        make test
    - name: Use dzil
      run: |
        perl -V
        cpan App::cpanminus
        cpanm --cpanfile cpanfile --installdeps --with-develop .
        dzil test
  unix:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    name: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Use Makefile.PL
      run: |
        perl -V
        cpan App::cpanminus
        cpanm --cpanfile cpanfile --installdeps --with-configure .
        perl Makefile.PL
        make
        make test
    - name: Use dzil
      run: |
        perl -V
        cpan App::cpanminus
        cpanm --cpanfile cpanfile --installdeps --with-develop .
        dzil test
