---
name: dzil build and test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
#  schedule:
#    - cron: "15 4 * * 0" # Every Sunday morning
  workflow_dispatch:

jobs:
  build-job:
    name: Build distribution
    runs-on: ubuntu-latest
    outputs:
      perl-minimum-version: ${{ steps.perl-minimum-version.outputs.version }}
    container:
      image: perldocker/perl-tester:5.36
    steps:
      - uses: actions/checkout@v2
      - name: Set PAUSE identity
        run: |
          echo user JDDPAUSE > ~/.pause
          echo password WellWellComeOn >> ~/.pause
      - name: Recuperate minimum perl version
        id: perl-minimum-version
        run: |
          cpm install JSON::MaybeXS
          perl -MJSON::MaybeXS -e 'print "version=" . decode_json(do { local $/; <STDIN> })->{prereqs}{configure}{requires}{perl} . "\n";' < META.json >> $GITHUB_OUTPUT
      - name: Run Tests
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
        run: |
          git config user.name "$GITHUB_ACTOR"
          upgrade-perl-helpers
          cpan-install-build-deps
          build-dist
          cd build_dir
          cpan-install-dist-deps --with-configure --with-develop
          perl Makefile.PL
          make
          prove -br t xt
          make clean
      - uses: actions/upload-artifact@master
        with:
          name: build_dir
          path: build_dir

  list-ubuntu-latest:
    needs: build-job
    name: Get perl versions on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install CPAN::Version
        run: |
          cpm install CPAN::Version
      - id: set-matrix
        name: List perl versions >= ${{needs.build-job.outputs.perl-minimum-version}}
        shell: perl {0}
        run: |
          use CPAN::Version;
          use Actions::Core;
          set_output(matrix => {perl => [grep { CPAN::Version->vcmp($_, "${{needs.build-job.outputs.perl-minimum-version}}") >= 0 } perl_versions()]});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-ubuntu-latest:
    runs-on: ubuntu-latest
    needs: list-ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list-ubuntu-latest.outputs.matrix)}}
    steps:
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry # this option only used on Windows
      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: .
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1
        with:
          cpanfile: "cpanfile"
          args: "--with-suggests --with-configure --with-recommends --with-test"
      - run: |
          perl Makefile.PL
          make
          make test

  list-macos-latest:
    needs: build-job
    name: Get perl versions on macos-latest
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install CPAN::Version
        run: |
          cpm install CPAN::Version
      - id: set-matrix
        name: List perl versions >= ${{needs.build-job.outputs.perl-minimum-version}}
        shell: perl {0}
        run: |
          use CPAN::Version;
          use Actions::Core;
          set_output(matrix => {perl => [grep { CPAN::Version->vcmp($_, "${{needs.build-job.outputs.perl-minimum-version}}") >= 0 } perl_versions()]});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-macos-latest:
    runs-on: macos-latest
    needs: list-macos-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list-macos-latest.outputs.matrix)}}
    steps:
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry # this option only used on Windows
      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: .
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1
        with:
          cpanfile: "cpanfile"
          args: "--with-suggests --with-configure --with-recommends --with-test"
      - run: |
          perl Makefile.PL
          make
          make test

  list-windows-latest:
    needs: build-job
    name: Get perl versions on windows-latest
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - name: Install CPAN::Version
        run: |
          cpm install CPAN::Version
      - id: set-matrix
        name: List perl versions >= ${{needs.build-job.outputs.perl-minimum-version}}
        shell: perl {0}
        run: |
          use CPAN::Version;
          use Actions::Core;
          set_output(matrix => {perl => [grep { CPAN::Version->vcmp($_, "${{needs.build-job.outputs.perl-minimum-version}}") >= 0 } perl_versions()]});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-windows-latest:
    runs-on: windows-latest
    needs: list-windows-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list-windows-latest.outputs.matrix)}}
    steps:
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry # this option only used on Windows
      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: .
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1
        with:
          cpanfile: "cpanfile"
          args: "--with-suggests --with-configure --with-recommends --with-test"
      - run: |
          perl Makefile.PL
          make
          make test
